### ISSUE TITLE
add "timeless" implication to unconjugated verbs

### ISSUE THREAD

**Issue by ackledotdev** [Transconlang/translang#65]
Proposal:
change the "-zim" suffix (currently means infinitive, so redundant) to "-zi" and have it imply an indefinite action with no defined beginning or end.
i.e. *'li nepetorizi mida* implies that the action is everlasting, compared to *'li nepetori**ne** mida*, which does not have quite the same meaning.
this would cut down on the length of sentences by reducing the need to say "always" or "forever" and also add an extra nuance to play around with

**Comment by akpi816218** [comment]
Awaiting poll results in Discord (24h)

**Comment by akpi816218** [comment]
Starting changes, poll 100% sim (10 votes) w/ 95m remaining
